apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: static-issuer
  namespace: static
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: saikrish793136@gmail.com
    privateKeySecretRef:
      name: static-issuer
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
